spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
server:
  servlet:
    session:
      cookie:
        secure: true  # HTTPS only in production
        same-site: strict

logging:
  level:
    com.restaurant: INFO
    org.springframework.security: WARN
